# Unix - Conda - Pip

We run commands in CLI, e.g., Terminal, but here we are using Jupyter Notebook to demonstrate:

1. Output from commands
2. That when experiementing or developing programs in the notebook, you can avoid switching tools.
3. That you can install pacakges in the beginning of the notebook (e.g., Sagemaker) so it's clear what packages are used.

## Unix commands

### Basics

For some of the basic commands, you can run use the cell to run it directly:

In [2]:
pwd # print working directory

'/home/tfarotimi/Fourth Brain Projects/Tope-Farotimi-MLE/assignments/week-01-mle-basictools/nb'

You always want to know "where you are" and how to look for help. Use `man` to display the user manual of any command that we can run on the terminal. 

In [3]:
man pwd # press ESC to exit

PWD(1)                    User Commands                   PWD(1)

NAME
       pwd - print name of current/working directory

SYNOPSIS
       pwd [OPTION]...

DESCRIPTION
       Print the full filename of the current working directory.

       -L, --logical
              use PWD from environment, even if it contains sym‐
              links

       -P, --physical
              avoid all symlinks

       --help display this help and exit

       --version
              output version information and exit

       If no option is specified, -P is assumed.

       NOTE: your shell may have its own version of  pwd,  which
       usually  supersedes  the  version described here.  Please
       refer to your shell's documentation for details about the
       options it supports.

AUTHOR
       Written by Jim Meyering.

REPORTING BUGS
       GNU  coreutils  online  help:  <https://www.gnu.org/soft‐
       ware/coreutils/>
       Report any translation bugs  to  <https://translationpro‐
       j

Further, cell magic `%%bash` turns a cell into a bash script where you can run multiple lines (See more cell/line magics [here](https://ipython.readthedocs.io/en/stable/interactive/magics.html)). 

In [4]:
%%bash
pwd
ls -lah # WE DO: What are those flags for?

/home/tfarotimi/Fourth Brain Projects/Tope-Farotimi-MLE/assignments/week-01-mle-basictools/nb
total 48K
drwxr-xr-x 2 tfarotimi tfarotimi 4.0K Dec  6 23:19 .
drwxr-xr-x 6 tfarotimi tfarotimi 4.0K Dec  6 23:19 ..
-rw-r--r-- 1 tfarotimi tfarotimi  37K Dec  6 23:19 unix-conda-pip.ipynb


### Download a data file

Let's download some data from [Census Income Data Set](https://archive.ics.uci.edu/ml/datasets/Census+Income); but first we would like to make a new directory to store the data at the same level as `nb` directory.

In [5]:
%%bash
cd ..
# WE DO: make a new diretory called `dat` under the project root directory


Let's confirm that we just created an empty directory `dat` using command `tree`. Not all command can be run in the cell directly, adding ! in front of command can do the trick:

In [6]:
!tree .. -L 2

..
├── README.md
├── dat
│   └── adult.csv
├── md
│   └── git-more.md
├── nb
│   └── unix-conda-pip.ipynb
└── pandas-sklearn-basics
    └── pandas-sklearn-basics.ipynb

4 directories, 5 files


In [7]:
# download a csv file
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data -O ../dat/adult.csv

--2022-12-07 02:06:40--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [application/x-httpd-php]
Saving to: ‘../dat/adult.csv’

../dat/adult.csv    100%[===================>]   3.79M   777KB/s    in 5.0s    

2022-12-07 02:06:47 (777 KB/s) - ‘../dat/adult.csv’ saved [3974305/3974305]



In [8]:
!tree .. -L 2 # check again

..
├── README.md
├── dat
│   └── adult.csv
├── md
│   └── git-more.md
├── nb
│   └── unix-conda-pip.ipynb
└── pandas-sklearn-basics
    └── pandas-sklearn-basics.ipynb

4 directories, 5 files


### Inspect data

Let's inspect first 10 lines of data:

In [9]:
!head ../dat/adult.csv

39, State-gov, 77516, Bachelors, 13, Never-married, Adm-clerical, Not-in-family, White, Male, 2174, 0, 40, United-States, <=50K
50, Self-emp-not-inc, 83311, Bachelors, 13, Married-civ-spouse, Exec-managerial, Husband, White, Male, 0, 0, 13, United-States, <=50K
38, Private, 215646, HS-grad, 9, Divorced, Handlers-cleaners, Not-in-family, White, Male, 0, 0, 40, United-States, <=50K
53, Private, 234721, 11th, 7, Married-civ-spouse, Handlers-cleaners, Husband, Black, Male, 0, 0, 40, United-States, <=50K
28, Private, 338409, Bachelors, 13, Married-civ-spouse, Prof-specialty, Wife, Black, Female, 0, 0, 40, Cuba, <=50K
37, Private, 284582, Masters, 14, Married-civ-spouse, Exec-managerial, Wife, White, Female, 0, 0, 40, United-States, <=50K
49, Private, 160187, 9th, 5, Married-spouse-absent, Other-service, Not-in-family, Black, Female, 0, 0, 16, Jamaica, <=50K
52, Self-emp-not-inc, 209642, HS-grad, 9, Married-civ-spouse, Exec-managerial, Husband, White, Male, 0, 0, 45, United-States, >50K
31, 

How about the last 3 lines? ( wait, I only see 2 lines. what's wrong? ) 

In [10]:
!tail -n 3 ../dat/adult.csv

22, Private, 201490, HS-grad, 9, Never-married, Adm-clerical, Own-child, White, Male, 0, 0, 20, United-States, <=50K
52, Self-emp-inc, 287927, HS-grad, 9, Married-civ-spouse, Exec-managerial, Wife, White, Female, 15024, 0, 40, United-States, >50K



How many records are there?

In [11]:
!wc -l ../dat/adult.csv

32562 ../dat/adult.csv


Challenge: how many columns are there?

In [12]:
!head -1 ../dat/adult.csv | sed 's/[^,]//g' | wc -c

15


## Conda: environment manager + package manager

You might have heard about Anaconda / Miniconda / Miniforge:

- What is the difference between `conda` and `miniconda`? [An answer](https://stackoverflow.com/questions/45421163/anaconda-vs-miniconda).
- What is the difference between `miniconda` and `miniforge`? [An answer](https://stackoverflow.com/questions/60532678/what-is-the-difference-between-miniconda-and-miniforge).

Though Conda is considered both a package manager and an environment manager, we  focus on using it as the environment manager, and use `pip` as the package manager.

### Installation

First, install `miniconda` (Feel free to skip if you have already installed it, or any flavor of conda).

Run the following commands in terminal to download the lastest Miniconda distribution and install it (Mac Intel Book). 

    ```
    cd ~
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    bash Miniconda3-latest-MacOSX-x86_64.sh
    ```

For M1 chip, install `miniforge` instead. If you are new to `brew`, following instructions [here](https://brew.sh) to install Homebrew first:

    ```
    brew install miniforge
    ```

Outputs from these installations are rather long, so we ask you to run it in a terminal window instead.

Confirm that the installation is successful:

In [13]:
%%bash
which conda  # where the executable conda is in my path?
conda -V     # which version of conda?
which python # where the executable python is in my path?
python -V    # what version of python?

/home/tfarotimi/anaconda3/condabin/conda
conda 4.10.3
/home/tfarotimi/anaconda3/envs/mlops-course/bin/python
Python 3.8.15


### Create a new env

Create a new conda environment named `py39_12` where you specify a python version to be 3.9.12. Note the last flag `--yes` to skip the confirmation prompt.

In [14]:
!conda create --name py39_12 python=3.9.12 --yes


CondaValueError: prefix already exists: /home/tfarotimi/anaconda3/envs/py39_12



In [16]:
# YOU CODE HERE 
# list all environments in conda
!conda env list

# conda environments:
#
base                     /home/tfarotimi/anaconda3
mlops-course          *  /home/tfarotimi/anaconda3/envs/mlops-course



You shall see something like this:
```
# conda environments:
#
                         /Users/flora/miniforge3
                         /Users/flora/miniforge3/envs/tf38
base                  *  /usr/local/Caskroom/miniforge/base
py39                     /usr/local/Caskroom/miniforge/base/envs/py39
py39_12                  /usr/local/Caskroom/miniforge/base/envs/py39_12
```

### Activate an env

By default, you are under the `base` environment, to activate the new environement, run `conda activate py39_12` in terminal.

If you are using VS code, click on the top right button to switch python kernel. You will be prompted to install `ipykernel`, follow the instructions to install the package. Or you can run `source activate`, followed by 
`conda activate /usr/local/Caskroom/miniforge/base/envs/py39_12` in a cell. 

If you are using jupyter notebook on a localhost (by defaut 8888), you can restart the jupyter notebook after activating the new environment.

Now verify the python version:

In [17]:
%%bash

python --version
which python
conda env list

Python 3.8.15
/home/tfarotimi/anaconda3/envs/mlops-course/bin/python
# conda environments:
#
base                     /home/tfarotimi/anaconda3
mlops-course          *  /home/tfarotimi/anaconda3/envs/mlops-course



<details>
<summary>Click to see how to add the Conda env to you jupyter notebook kernels</summary>

```
pip install ipykernel
python -m ipykernel install --user --name=py39_12
```

Next time you launch jupyter notebook, you will see `py39_12` as an option under Kernel/Change kernel.
</details>




### Delete an env

To keep a lean list of environments, we want to prune unused environements from time to time. Simply do the following
```
conda remove --name old_env --all --yes
```

## Pip: python package manager

We recommend to use pip as your python package installer/manager [(fun read on pip vs conda.)](https://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda) Note you don't have install pip explictly since it was done during the installation of miniconda/miniforge. 

In [18]:
!which pip

/home/tfarotimi/anaconda3/envs/mlops-course/bin/pip


### Install package

We can certainly run `pip` commands the same way as earlier. Just for fun, let's try Jupyter line magic `%pip`. 

First make sure that we would like to have the most recent version of `pip` installed.

In [19]:
%pip install --upgrade pip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 597.6 kB/s eta 0:00:0000:0100:01
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Note: you may need to restart the kernel to use updated packages.


In [1]:
#%pip install seaborn

import seaborn as sns

Now you can use these packages:

In [2]:
# allow multiple outputs in a single cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [10]:
import numpy as np

# create a numpy array with random numbers
x = np.random.rand(10)
x.shape
x
x.reshape((5,-1))


(10,)

array([0.21565212, 0.37028688, 0.29106468, 0.3098387 , 0.0808734 ,
       0.89297847, 0.6864952 , 0.22027712, 0.11152747, 0.78917778])

array([[0.21565212, 0.37028688],
       [0.29106468, 0.3098387 ],
       [0.0808734 , 0.89297847],
       [0.6864952 , 0.22027712],
       [0.11152747, 0.78917778]])

In [11]:
%precision 3
x.reshape((5,-1))

'%.3f'

array([[0.216, 0.37 ],
       [0.291, 0.31 ],
       [0.081, 0.893],
       [0.686, 0.22 ],
       [0.112, 0.789]])

In [12]:
import pandas as pd
census_df = pd.read_csv(filepath_or_buffer='../dat/adult.csv', header = None)
census_df.head()
census_df.tail()
census_df.shape

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

0              1       2            3   4                    5   \
32556  27        Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40        Private  154374      HS-grad   9   Married-civ-spouse   
32558  58        Private  151910      HS-grad   9              Widowed   
32559  22        Private  201490      HS-grad   9        Never-married   
32560  52   Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6           7       8        9      10  11  12  \
32556        Tech-support        Wife   White   Female      0   0  38   
32557   Machine-op-inspct     Husband   White     Male      0   0  40   
32558        Adm-clerical   Unmarried   White   Female      0   0  40   
32559        Adm-clerical   Own-child   White     Male      0   0  20   
32560     Exec-managerial        Wife   White   Female  15024   0  40   

                   13      14  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K

(32561, 15)

### Uninstall packages

In [13]:
# Uninstall a package
%pip uninstall numpy pandas --yes

Found existing installation: numpy 1.23.5
Uninstalling numpy-1.23.5:
  Successfully uninstalled numpy-1.23.5
Found existing installation: pandas 1.5.2
Uninstalling pandas-1.5.2:
  Successfully uninstalled pandas-1.5.2
Note: you may need to restart the kernel to use updated packages.


In [14]:
%pip cache purge

Files removed: 182
Note: you may need to restart the kernel to use updated packages.
